// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB4nJ9NSddjyHH6nm316UI9Zh_IYP8fEs',
    appId: '1:715828755705:web:d33fe1586cc3f7220d7628',
    messagingSenderId: '715828755705',
    projectId: 'flutter-auth-7f95b',
    authDomain: 'flutter-auth-7f95b.firebaseapp.com',
    storageBucket: 'flutter-auth-7f95b.appspot.com',
    measurementId: 'G-YDFX6GWWYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKLe2CgsjdVtXb2Oysjgj7rMPoSVVNAh8',
    appId: '1:715828755705:android:c73c52f9305b42ae0d7628',
    messagingSenderId: '715828755705',
    projectId: 'flutter-auth-7f95b',
    storageBucket: 'flutter-auth-7f95b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNFKwSt6zJIreddO0rYxtSpkTPn38H_Q',
    appId: '1:715828755705:ios:5916d05b0265ce430d7628',
    messagingSenderId: '715828755705',
    projectId: 'flutter-auth-7f95b',
    storageBucket: 'flutter-auth-7f95b.appspot.com',
    iosClientId: '715828755705-vsdcv1ntr6q1tu3veseb0uohj6niiqcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailsign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoNFKwSt6zJIreddO0rYxtSpkTPn38H_Q',
    appId: '1:715828755705:ios:5916d05b0265ce430d7628',
    messagingSenderId: '715828755705',
    projectId: 'flutter-auth-7f95b',
    storageBucket: 'flutter-auth-7f95b.appspot.com',
    iosClientId: '715828755705-vsdcv1ntr6q1tu3veseb0uohj6niiqcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailsign',
  );
}
